spring.config.activate.on_profile: dev
spring:
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-version: 1

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/motte?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: admin
    password: password

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate

---
spring.config.activate.on_profile: prod
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.dbname}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: ${rds.username}
    password: ${rds.password}
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: none